### ISSUE TITLE
add staticcheck to github CI workflow

### ISSUE THREAD

**Issue by padlar** [statnett/controller-runtime-viper#8]
I have previously used these steps to run [staticcheck](https://staticcheck.io/):

```yaml
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...
```

But I notice that there exist a dedicated action for this: https://github.com/marketplace/actions/staticcheck . 

Do you have any experience with staticcheck and/or think it could be useful in this project?

_Originally posted by @mikaelol in https://github.com/statnett/controller-runtime-viper/issues/2#issuecomment-1339196568_
